name: point2mesh
channels:
  - pytorch
  - defaults
  - conda-forge
  - fvcore
dependencies:
  - python=3.7.9
  - numpy=1.18.1
  - pytorch=1.5.0
  - cudatoolkit=10.2  # Remove if using CPU-only
  - fvcore=0.1
  - pip
  - pip:
    - torchvision==0.6.0  # Install without +cpu suffix
    - git+https://github.com/facebookresearch/pytorch3d.git@v0.2.0  # Install from source
    - pytest==5.4.2